<?php
/*
 * Copyright MADE/YOUR/DAY OG <mail@madeyourday.net>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace MadeYourDay\RockSolidSlider\Module;

/**
 * Slider Events Module
 *
 * @author Martin Auswöger <martin@madeyourday.net>
 */
class SliderEvents extends \MadeYourDay\RockSolidSlider\SlideProvider\Bridge\ContaoEvents
{
	/**
	 * Get an array of events (HTML output) generated by Contao\ModuleEventlist
	 *
	 * @return array Events HTML output or an empty array if no events are found.
	 */
	public function getEventItems()
	{
		$slides   = parent::getSlides();
		$articles = [];
		foreach ($slides as $slide) {
			$articles[] = $slide['text'];
		}
		return $articles;
	}
}
