<?php
/*
 * Copyright MADE/YOUR/DAY OG <mail@madeyourday.net>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace MadeYourDay\RockSolidSlider\Module;

@trigger_error('Class MadeYourDay\RockSolidSlider\Module\SliderNews is deprecated and will get removed.', E_USER_DEPRECATED);

/**
 * Slider News Module
 *
 * @author Martin Auswöger <martin@madeyourday.net>
 */
class SliderNews extends \MadeYourDay\RockSolidSlider\SlideProvider\Bridge\ContaoNews
{
	/**
	 * Get an array of news articles (HTML output) generated by Contao\ModuleNewsList
	 *
	 * @return array News HTML output or an empty array if no news are found.
	 */
	public function getNewsArticles()
	{
		$slides   = parent::getSlides();
		$articles = [];
		foreach ($slides as $slide) {
			$articles[] = $slide['text'];
		}
		return $articles;
	}
}
